In [20]:
import pandas as pd
import math

In [21]:
ratingsFile = pd.read_csv('test.csv')
ratings = ratingsFile.set_index(['userId', 'movieId'])
ratings

                rating
userId movieId
1      1           1.0
       2           2.0
       3           3.0
       4           4.0
2      2           4.0
       3           3.0
       4           2.0
       5           1.0
3      1           2.0
       2           2.0
       3           5.0
4      3           2.0
       4           2.0
       5           5.0
5      1           3.0
       3           5.0
       5           3.0

In [22]:
math.sqrt((ratings.loc[1]**2).sum())

5.477225575051661

In [38]:
dictLength = {}
users = ratings.index.levels[0]
for i in users:
    dictLength[i]=math.sqrt((ratings.loc[i]**2).sum())

In [45]:
dictMean = {}
users = ratings.index.levels[0]
for i in users:
    dictMean[i]=(ratings.loc[i]).mean()

In [60]:
ratings2 = ratings.reset_index().sort_values('movieId').set_index(['movieId', 'userId'])
ratings2

                rating
movieId userId
1       1          1.0
        5          3.0
        3          2.0
2       2          4.0
        3          2.0
        1          2.0
3       2          3.0
        5          5.0
        3          5.0
        4          2.0
        1          3.0
4       1          4.0
        2          2.0
        4          2.0
5       2          1.0
        4          5.0
        5          3.0

In [61]:
dictionary = {}

In [62]:
dictionary

{}

In [63]:
dictionary['ricky']='asdf'
dictionary['peng']='adfsad'
dictionary

{'ricky': 'asdf', 'peng': 'adfsad'}

In [64]:
dictionary['ricky']

'asdf'

In [65]:
ratingsFile

    userId  movieId  rating
0        1        1     1.0
1        1        2     2.0
2        1        3     3.0
3        1        4     4.0
4        2        2     4.0
5        2        3     3.0
6        2        4     2.0
7        2        5     1.0
8        3        1     2.0
9        3        2     2.0
10       3        3     5.0
11       4        3     2.0
12       4        4     2.0
13       4        5     5.0
14       5        1     3.0
15       5        3     5.0
16       5        5     3.0

In [66]:
ratings

                rating
userId movieId
1      1           1.0
       2           2.0
       3           3.0
       4           4.0
2      2           4.0
       3           3.0
       4           2.0
       5           1.0
3      1           2.0
       2           2.0
       3           5.0
4      3           2.0
       4           2.0
       5           5.0
5      1           3.0
       3           5.0
       5           3.0

In [73]:
rrr=ratings.groupby('movieId').mean().loc[1]
rrr

rating    2.0
Name: 1, dtype: float64

In [71]:
rrr.loc[1]

rating    2.0
Name: 1, dtype: float64

In [74]:
ratings.loc[1]

         rating
movieId
1           1.0
2           2.0
3           3.0
4           4.0

In [75]:
ratings.loc[2]

         rating
movieId
2           4.0
3           3.0
4           2.0
5           1.0

In [76]:
 = ratings.loc[1].index.intersection(ratings.loc[2].index)
list

Int64Index([2, 3, 4], dtype='int64', name='movieId')

In [80]:
from typing import Dict
cache: Dict[int, Dict] = {}

In [86]:
cache = {}
cache[1]={}
cache[1]['2']='3'
cache

{1: {'2': '3'}}

In [92]:
ttt=ratings.index.levels[0]

In [97]:
ratings

                rating
userId movieId
1      1           1.0
       2           2.0
       3           3.0
       4           4.0
2      2           4.0
       3           3.0
       4           2.0
       5           1.0
3      1           2.0
       2           2.0
       3           5.0
4      3           2.0
       4           2.0
       5           5.0
5      1           3.0
       3           5.0
       5           3.0

In [98]:
ratings.index.levels[1]

Int64Index([1, 2, 3, 4, 5], dtype='int64', name='movieId')

In [107]:
can=[1,2,8,4,5]

In [108]:
can

[1, 2, 8, 4, 5]

In [109]:
can2 = can[0:2]

In [111]:
can2

[1, 2]

In [112]:
ratings

                rating
userId movieId
1      1           1.0
       2           2.0
       3           3.0
       4           4.0
2      2           4.0
       3           3.0
       4           2.0
       5           1.0
3      1           2.0
       2           2.0
       3           5.0
4      3           2.0
       4           2.0
       5           5.0
5      1           3.0
       3           5.0
       5           3.0

In [114]:
ratings.loc[1].mean()

rating    2.5
dtype: float64